apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    kind: web
    target: staging
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
