FROM debian AS build
RUN mkdir /build
RUN echo "Hello" > /build/content.txt

FROM debian AS test
RUN echo "Test Result"

FROM debian AS release
RUN apt update && apt install npm -y
RUN mkdir /app
WORKDIR /app
COPY package.json .
COPY package-lock.json .
COPY --from=build /build/content.txt /app
RUN npm i
COPY --from=build /build /app
EXPOSE 8080
CMD ["node", "-r", "ts-node/register", "/app/server.ts"]